### ISSUE TITLE
Any plans to add some form of reporting such as email

### ISSUE THREAD

**Issue by Tigger2014** [plattfot/baksnapper#5]
Hi there, great work, this is the only btrfs backup script ive found that will work with my nas perfectly.

i wondered if there were any plans to be able to get a report on the status or even just alerts when the job fails for whatever reason?

Thanks

**Comment by plattfot** [comment]
Thank you, I'm glad it's useful for you.

No plans to extend baksnapper to support these kind of features. I'm leaving that to the job scheduler (whether that be systemd-timer, cron or something else) as they do a far better job than baksnapper could do. I do plan to improve the output when running baksnapper. Right now it's a bit sparse.

There are some support for libnotify, but turned out to not be that useful for me as I run it via systemd-timer. Not sure if I'll keep that around or not.

If you are using systemd-timer, you can do something like this to email you when it fails (or when it's done):

Edit the `baksnapper@.service` using `systemctl edit` add:
```
[Unit]
OnFailure=email-after@%n.service

[Service]
ExecStartPost=/bin/systemctl start email-after@%n.service
```
The `OnFailure` will run `email-after@.service` if the service fails for some reason. The `ExecStartPost` will run `email-after@.service` after it is done.
 
`email-after@.service` is:
```
[Unit]
Description=Sends an email after %i is done  

[Service]
User=root
Type=oneshot
ExecStart=<path to mail.sh> %i
```
Where `<path to mail.sh>` is the path to a script that sends the email. Something like this will work:
```bash
#! /bin/bash

read -rd '' help <<EOF
Usage: $0 [OPTIONS]... --from=FROM --to=TO UNIT

Send an email with the status from the latest run of UNIT.
Options:
  -f, --from <name@domain.com> Address to use as sender.
  -t, --to <name@domain.com>   Address to send the email to.
  -h, --help                   Print this message and quit.
  -n, --dry-run                Print email instead of sending it.
Author:
Fredrik "PlaTFooT" Salomonsson
EOF

_args=$(getopt --options "f:t:hn" --long "from:,to:,help,dry-run" -- "$@")
if [[ $? != 0 ]]
then
    echo "Try '$0 --help for more information.'" >&2
    exit $1
fi

eval set -- "$_args"

while [[ $# > 0 ]]
do
key=$1
case $key in
    -f|--from)
        from="$2"
        shift 2
        ;;
    -t|--to)
        to="$2"
        shift 2
        ;;
    -h|--help)
        echo -e "$help"
        exit 0
        ;;
    -n|--dry-run)
	dry_run=1
	shift
	;;
    --)
        shift
        break
        ;;
esac
done

unit=$1

function error-opt {
    echo "$1' need to be specified" >&2
    echo "Try '$0 --help for more information.'" >&2
    exit 1
}

if [[ "$unit" == "" ]]
then
    error-opt "unit"
fi

if [[ "$from" == "" ]]
then
    error-opt "from"
fi

if [[ "$to" == "" ]]
then
    error-opt "to"
fi

dry_run=${dry_run-0}

[[ -z $unit ]] && echo "No unit specified!" && exit 1

msg="$(systemctl status $unit -l -n 99999 --no-pager)"
mail="To: $to\nFrom: $from\nSubject: Status from $unit\n\n$msg"
if [[ $dry_run != 1 ]]
then
    echo -e "$mail" | msmtp --read-envelope-from $to
else
    echo -e "$mail"
fi
``` 
Although, after writing this. Maybe it would be a good idea to include these as example scripts in the systemd directory.

**Comment by plattfot** [comment]
Closing this issue, out of scope for this project to include any form of reporting such as email.
